from __future__ import annotations

SETTINGS_VALIDATION_FAILED = "SETTINGS_VALIDATION_FAILED"
RUN_ALREADY_ACTIVE = "RUN_ALREADY_ACTIVE"
INVALID_MODE = "INVALID_MODE"
RUN_NOT_FOUND = "RUN_NOT_FOUND"
RUN_NOT_PAUSABLE = "RUN_NOT_PAUSABLE"
RUN_NOT_RESUMABLE = "RUN_NOT_RESUMABLE"
RUN_NOT_CANCELLABLE = "RUN_NOT_CANCELLABLE"
INVALID_PAYLOAD = "INVALID_PAYLOAD"
INTERNAL_ERROR = "INTERNAL_ERROR"
INCREMENTAL_STATUS_FAILED = "INCREMENTAL_STATUS_FAILED"
VISUALIZATION_INDEX_FAILED = "VISUALIZATION_INDEX_FAILED"

